-- =====================================================================
--  Blood Bank Cloud — canonical PostgreSQL schema
-- =====================================================================
--  This is the source-of-truth schema for a *production* deployment
--  (e.g. AWS RDS for PostgreSQL). It intentionally mirrors the column
--  names the application/ORM uses (quoted camelCase, Sequelize's default)
--  so the running app works against it unchanged — but it adds the
--  database-level guarantees that `sequelize.sync()` does NOT create:
--
--    * native ENUM types               * CHECK constraints
--    * foreign keys with ON DELETE      * purposeful indexes (incl. partial)
--    * case-insensitive unique email    * updated_at triggers
--    * reporting views                  * column/table documentation
--
--  In development the app still uses `sequelize.sync()` against SQLite or a
--  local Postgres. In production set DB_SYNC=false and provision with this
--  file (or run it via `docker compose` — it is mounted as an init script).
--
--  Apply manually:   psql "$DATABASE_URL" -f backend/db/schema.sql
--  It is idempotent — safe to run repeatedly.
-- =====================================================================

BEGIN;

-- --------------------------------------------------------------------
-- Enum types (created once; guarded so re-runs don't error)
-- --------------------------------------------------------------------
DO $$ BEGIN
  CREATE TYPE blood_group AS ENUM ('A+','A-','B+','B-','AB+','AB-','O+','O-');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE urgency_level AS ENUM ('low','medium','high','critical');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE request_status AS ENUM ('open','matched','fulfilled','cancelled');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- --------------------------------------------------------------------
-- Shared updated_at trigger
-- --------------------------------------------------------------------
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS trigger AS $$
BEGIN
  NEW."updatedAt" = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- --------------------------------------------------------------------
-- Donors
-- --------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "Donors" (
  "id"            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name"          text         NOT NULL CHECK (length(btrim("name")) BETWEEN 1 AND 120),
  "email"         text         NOT NULL CHECK (position('@' in "email") > 1),
  "phone"         text         NOT NULL CHECK (length(btrim("phone")) BETWEEN 3 AND 32),
  "bloodGroup"    blood_group  NOT NULL,
  "city"          text         NOT NULL CHECK (length(btrim("city")) BETWEEN 1 AND 120),
  "lastDonatedAt" timestamptz,
  "available"     boolean      NOT NULL DEFAULT true,
  "createdAt"     timestamptz  NOT NULL DEFAULT now(),
  "updatedAt"     timestamptz  NOT NULL DEFAULT now()
);

-- Case-insensitive uniqueness: asha@x.com and Asha@X.com are the same donor.
CREATE UNIQUE INDEX IF NOT EXISTS donors_email_lower_key ON "Donors" (lower("email"));
-- Donor matching filters by availability + group + city; this partial index
-- serves the hot path (only available donors are ever matched).
CREATE INDEX IF NOT EXISTS donors_match_idx
  ON "Donors" ("bloodGroup", "city", "lastDonatedAt")
  WHERE "available";

DROP TRIGGER IF EXISTS donors_set_updated_at ON "Donors";
CREATE TRIGGER donors_set_updated_at BEFORE UPDATE ON "Donors"
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- --------------------------------------------------------------------
-- Hospitals
-- --------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "Hospitals" (
  "id"           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name"         text        NOT NULL CHECK (length(btrim("name")) BETWEEN 1 AND 160),
  "city"         text        NOT NULL,
  "contactEmail" text        NOT NULL CHECK (position('@' in "contactEmail") > 1),
  "contactPhone" text        NOT NULL,
  "createdAt"    timestamptz NOT NULL DEFAULT now(),
  "updatedAt"    timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS hospitals_city_idx ON "Hospitals" ("city");

DROP TRIGGER IF EXISTS hospitals_set_updated_at ON "Hospitals";
CREATE TRIGGER hospitals_set_updated_at BEFORE UPDATE ON "Hospitals"
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- --------------------------------------------------------------------
-- BloodInventories — one row per blood group
-- --------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "BloodInventories" (
  "id"         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "bloodGroup" blood_group NOT NULL UNIQUE,
  "units"      integer     NOT NULL DEFAULT 0 CHECK ("units" >= 0 AND "units" <= 1000000),
  "createdAt"  timestamptz NOT NULL DEFAULT now(),
  "updatedAt"  timestamptz NOT NULL DEFAULT now()
);

DROP TRIGGER IF EXISTS inventory_set_updated_at ON "BloodInventories";
CREATE TRIGGER inventory_set_updated_at BEFORE UPDATE ON "BloodInventories"
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- Ensure every blood group exists at zero stock (idempotent).
INSERT INTO "BloodInventories" ("bloodGroup", "units")
SELECT g::blood_group, 0
FROM unnest(ARRAY['A+','A-','B+','B-','AB+','AB-','O+','O-']) AS g
ON CONFLICT ("bloodGroup") DO NOTHING;

-- --------------------------------------------------------------------
-- BloodRequests
-- --------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "BloodRequests" (
  "id"          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "patientName" text           NOT NULL CHECK (length(btrim("patientName")) BETWEEN 1 AND 160),
  "bloodGroup"  blood_group    NOT NULL,
  "unitsNeeded" integer        NOT NULL DEFAULT 1 CHECK ("unitsNeeded" BETWEEN 1 AND 100),
  "urgency"     urgency_level  NOT NULL DEFAULT 'medium',
  "status"      request_status NOT NULL DEFAULT 'open',
  "hospitalId"  integer        NOT NULL REFERENCES "Hospitals" ("id") ON DELETE RESTRICT,
  "createdAt"   timestamptz    NOT NULL DEFAULT now(),
  "updatedAt"   timestamptz    NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS requests_hospital_idx ON "BloodRequests" ("hospitalId");
-- Open/unfulfilled requests are queried constantly; index just those.
CREATE INDEX IF NOT EXISTS requests_open_idx
  ON "BloodRequests" ("status", "createdAt" DESC)
  WHERE "status" IN ('open','matched');

DROP TRIGGER IF EXISTS requests_set_updated_at ON "BloodRequests";
CREATE TRIGGER requests_set_updated_at BEFORE UPDATE ON "BloodRequests"
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- --------------------------------------------------------------------
-- Donations
-- --------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "Donations" (
  "id"         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "donorId"    integer     NOT NULL REFERENCES "Donors" ("id") ON DELETE CASCADE,
  "bloodGroup" blood_group NOT NULL,
  "units"      integer     NOT NULL DEFAULT 1 CHECK ("units" BETWEEN 1 AND 100),
  "donatedAt"  timestamptz NOT NULL DEFAULT now(),
  "createdAt"  timestamptz NOT NULL DEFAULT now(),
  "updatedAt"  timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS donations_donor_idx ON "Donations" ("donorId");
CREATE INDEX IF NOT EXISTS donations_donated_at_idx ON "Donations" ("donatedAt");
-- Supports the "donations per month per group" analytics rollup.
CREATE INDEX IF NOT EXISTS donations_group_month_idx
  ON "Donations" ("bloodGroup", "donatedAt");

DROP TRIGGER IF EXISTS donations_set_updated_at ON "Donations";
CREATE TRIGGER donations_set_updated_at BEFORE UPDATE ON "Donations"
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- --------------------------------------------------------------------
-- Reporting views (read-only convenience for BI tools / dashboards)
-- --------------------------------------------------------------------
CREATE OR REPLACE VIEW low_stock_inventory AS
  SELECT "bloodGroup", "units"
  FROM "BloodInventories"
  WHERE "units" < COALESCE(NULLIF(current_setting('app.low_stock_threshold', true), '')::int, 5)
  ORDER BY "units" ASC;

CREATE OR REPLACE VIEW monthly_donation_trends AS
  SELECT to_char("donatedAt", 'YYYY-MM') AS month,
         "bloodGroup",
         count(*)        AS donations,
         sum("units")    AS units
  FROM "Donations"
  GROUP BY 1, 2
  ORDER BY 1 ASC;

-- --------------------------------------------------------------------
-- Documentation
-- --------------------------------------------------------------------
COMMENT ON TABLE  "Donors"           IS 'Registered blood donors. email/phone/blood group are personal & health data — see PRIVACY.md.';
COMMENT ON COLUMN "Donors"."bloodGroup" IS 'Special-category health data under GDPR.';
COMMENT ON TABLE  "BloodInventories" IS 'Current units in stock, one row per blood group; units can never go negative.';
COMMENT ON TABLE  "BloodRequests"    IS 'Recipient/patient requests; fulfilment decrements inventory transactionally.';
COMMENT ON TABLE  "Donations"        IS 'Donation events; increments inventory and stamps the donor''s lastDonatedAt.';

COMMIT;
